site_name: Simple Docs
site_description: Contributor-friendly MkDocs starter

theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - content.code.copy

plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - tables
  - toc:
      permalink: true

nav:
  - Landing Page: landing-page.md
  - OSSM Specs: ossm-specs.md
  - OSSM BOM: ossm-bom.md
  - How to Use: how-to-use.md
  - Writer's Guide:
      - Overview: index.md
      - Getting Started: getting-started.md
      - Writing Guide: writing-guide.md
      - Contributing: contributing.md
