site_name: Research and Desire Product Documentation
site_description: Quick-start guide and reference for Research and Desire products.
site_url: https://docs.researchanddesire.com

theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - content.code.copy

plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - tables
  - toc:
      permalink: true

nav:
  - Landing Page: landing-page.md
  - OSSM Specs: ossm-specs.md
  - OSSM BOM: ossm-bom.md
  - How to Use: how-to-use.md
  - MK Docs Overview: index.md
  - MKDocs Getting Started: getting-started.md
  - MKDocs Writing Guide: writing-guide.md
  - MKDocs Contributing: contributing.md
  - Integrations: integrations.md
